route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhooker-slack'
receivers:
  - name: 'webhooker-slack'
    webhook_configs:
      - url: 'URL'
    slack_configs:
     - api_url: SLACK_URL
       channel: '-dev-ccx-alertmgr-test'
       send_resolved: true
       icon_url: https://avatars3.githubusercontent.com/u/3380462
       text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Description:* {{ .Annotations.description }}
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

